version: "3.8"

services:
  app:
    build: .
    container_name: my_python_app
    volumes:
      - .:/app
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TOKEN_MERCADO_LIVRE=${TOKEN_MERCADO_LIVRE}
      - CHAT_ID=${CHAT_ID}

    restart: unless-stopped
